services:
  postgres:
    image: postgres:latest
    ports: 
      - 5432:5432
    container_name: postgres-server
    environment:
      POSTGRES_USER: nelson
      POSTGRES_PASSWORD: isS3cur3P@ssw0rd!
      POSTGRES_DB: prueba
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres.network
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-server
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin-nelson@superadmin.com
      PGADMIN_DEFAULT_PASSWORD: isS3cur3P@ssw0rd!
    ports:
      - "9908:80"
    depends_on:
      - postgres
    networks:
      - postgres.network
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  postgres.network:
    driver: bridge