services:
  golang.webdata:
    restart: "always"
    container_name: golang.webdata
    volumes:
      - golang_webdata_data:/go/src/app
      - .:/go/src/app  # Montar el directorio actual para desarrollo
    build:
      context: .
      dockerfile: golang.dev.Dockerfile
    ports:
      - "9000:9000"
    networks:
      - postgres_postgres.network
    command: air  # Ejecutar air en lugar del comando por defecto


volumes:
  golang_webdata_data:
    driver: local

networks:
  postgres_postgres.network:
    external: true