// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package schemas

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type History struct {
	ID        int64            `json:"id"`
	Money     string           `json:"money"`
	Source    string           `json:"source"`
	SourceWeb string           `json:"source_web"`
	Change    float64          `json:"change"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Payment struct {
	ID             int64            `json:"id"`
	SubscriptionID int64            `json:"subscription_id"`
	Amount         pgtype.Numeric   `json:"amount"`
	PaymentDate    pgtype.Timestamp `json:"payment_date"`
	PaymentMethod  string           `json:"payment_method"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
}

type Subscription struct {
	ID        int64            `json:"id"`
	UserID    int64            `json:"user_id"`
	StartDate pgtype.Timestamp `json:"start_date"`
	EndDate   pgtype.Timestamp `json:"end_date"`
	Status    string           `json:"status"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type User struct {
	ID        int64            `json:"id"`
	Email     string           `json:"email"`
	Password  string           `json:"password"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}
